name: Process Word Submission

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write

jobs:
  add:
    runs-on: ubuntu-22.04
    if: contains(github.event.issue.labels.*.name, 'new-word')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add Words to JSON
        run: docker run --rm -e CI=true -e GH_BODY="$GH_BODY" -v "$PWD:/host" -w /host swiftlang/swift:nightly-6.0-focal swift .github/scripts/add.swift
        id: add
        env:
          GH_BODY: ${{ github.event.issue.body }}

      - name: Validate JSON
        run: docker run --rm -e CI=true -e GH_BODY="$GH_BODY" -v "$PWD:/host" -w /host swift:nightly-6.0-focal swift .github/scripts/validate.swift
        id: validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Changes
        run: bash .github/scripts/check_for_changes.sh
        id: check

      - name: Create Pull Request
        id: cpr
        if: steps.check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            Sources/PhraseKit/Resources/_adjective.json
            Sources/PhraseKit/Resources/_adverb.json
            Sources/PhraseKit/Resources/_noun.json
            Sources/PhraseKit/Resources/_verb.json
          commit-message: ${{ github.event.issue.title }}
          title: ${{ github.event.issue.title }}
          branch: auto-add-${{ github.event.issue.number }}
          delete-branch: true
          body: |
            Closes #${{ github.event.issue.number }}

            ## Original Message

            ${{ github.event.issue.body }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>

      - name: Update Issue (Success)
        if: steps.check.outputs.changes == 'true'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you! We will approve and add these words with #${{ steps.cpr.outputs.pull-request-number }}.'
            })

      - name: Update Issue (Failure)
        if: ${{ failure() || steps.check.outputs.changes != 'true' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'It looks like there’s nothing to do here!\n\nPlease ensure your submission contains valid words.'
            })
