name: Validate and Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.labels.*.name, 'mb-cli')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Validation Script
        id: validation
        run: |
          node ./.github/scripts/scanner.js ./Sources/PhraseKit/Resources/ pending

      - name: Merge Pull Request
        if: success()
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ env.BOT_ACCESS_TOKEN }}


      - name: Comment on Failure
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('validation_output.txt', 'utf8');
            github.pulls.createReview({
              pull_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Validation failed with the following details:\n\`\`\`\n${output}\n\`\`\`\nPlease check the details and make necessary changes.`,
              event: "REQUEST_CHANGES"
            });
