name: Validate and Merge Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.labels.*.name, 'mb-cli')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Validation Script
        id: validation
        run: |
          node ./.github/scripts/scanner.js ./Sources/PhraseKit/Resources/ pending

      - name: Comment on Validation Results
        if: success() || failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('validation_output.txt', 'utf8');
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: `Validation results:\n\n\`\`\`\n${output}\n\`\`\``,
              event: 'COMMENT'
            })
  
      - name: Comment on Failure
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: 'Validation failed. Please check the details and make necessary changes.',
              event: 'REQUEST_CHANGES'
            })
  